export const NumbersEXP = [
    {
        position: "one",
        values:[
           {
               value:"valueNorth",
               image:"imageSRC"
           },
           {
                value:"valueSouth",
                image:"imageSRC"
           },
           {
                value:"valueLest",
                image:"imageSRC"
           },
           {
                value:"valueWest",
                image:"imageSRC"
           }
        ] 
    },
    {
        position: "two",
        values:[
           {
               value:"valueNorth",
               image:"imageSRC"
           },
           {
                value:"valueSouth",
                image:"imageSRC"
           },
           {
                value:"valueLest",
                image:"imageSRC"
           },
           {
                value:"valueWest",
                image:"imageSRC"
           }
        ] 
    },
    {
        position: "three",
        values:[
           {
               value:"valueNorth",
               image:"imageSRC"
           },
           {
                value:"valueSouth",
                image:"imageSRC"
           },
           {
                value:"valueLest",
                image:"imageSRC"
           },
           {
                value:"valueWest",
                image:"imageSRC"
           }
        ] 
    },
    {
        position: "four",
        values:[
           {
               value:"valueNorth",
               image:"imageSRC"
           },
           {
                value:"valueSouth",
                image:"imageSRC"
           },
           {
                value:"valueLest",
                image:"imageSRC"
           },
           {
                value:"valueWest",
                image:"imageSRC"
           }
        ] 
    },
    {
        position: "five",
        values:[
           {
               value:"valueNorth",
               image:"imageSRC"
           },
           {
                value:"valueSouth",
                image:"imageSRC"
           },
           {
                value:"valueLest",
                image:"imageSRC"
           },
           {
                value:"valueWest",
                image:"imageSRC"
           }
        ] 
    },
    {
        position: "six",
        values:[
           {
               value:"valueNorth",
               image:"imageSRC"
           },
           {
                value:"valueSouth",
                image:"imageSRC"
           },
           {
                value:"valueLest",
                image:"imageSRC"
           },
           {
                value:"valueWest",
                image:"imageSRC"
           }
        ] 
    },
    {
        position: "seven",
        values:[
           {
               value:"valueNorth",
               image:"imageSRC"
           },
           {
                value:"valueSouth",
                image:"imageSRC"
           },
           {
                value:"valueLest",
                image:"imageSRC"
           },
           {
                value:"valueWest",
                image:"imageSRC"
           }
        ] 
    },
    {
        position: "eight",
        values:[
           {
               value:"valueNorth",
               image:"imageSRC"
           },
           {
                value:"valueSouth",
                image:"imageSRC"
           },
           {
                value:"valueLest",
                image:"imageSRC"
           },
           {
                value:"valueWest",
                image:"imageSRC"
           }
        ] 
    },
    {
        position: "nine",
        values:[
           {
               value:"valueNorth",
               image:"imageSRC"
           },
           {
                value:"valueSouth",
                image:"imageSRC"
           },
           {
                value:"valueLest",
                image:"imageSRC"
           },
           {
                value:"valueWest",
                image:"imageSRC"
           }
        ] 
    }
]
